site_name: Team Dokumentation
site_description: Vores herre seje dokumentation
site_author: womp

theme:
  name: material #Eller readthedocs som navn

nav:
  - Home: index.md
  - About: about.md
  - TESTER: test.md
